### ISSUE TITLE
Plugin can't load

### ISSUE THREAD

**Issue by pipoprods** [willothy/blam.nvim#2]
Hi,

I'm using the same NeoVim config on 3 different hosts (all Debian stable). Il's working fine on 1 of the hosts but fails on the two others.
I've got this trace:

```
E5108: Error executing lua /home/sni/.local/share/nvim/lazy/blam.nvim/lua/blam.lua:76: module 'blam.core' not found:
        no field package.preload['blam.core']
lazy_loader: module blam.core not found
lazy_loader_lib: module blam.core not found
        no file './blam/core.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/blam/core.lua'
        no file '/usr/local/share/lua/5.1/blam/core.lua'
        no file '/usr/local/share/lua/5.1/blam/core/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/blam/core.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/blam/core/init.lua'
        no file './blam/core.so'
        no file '/usr/local/lib/lua/5.1/blam/core.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/blam/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './blam.so'
        no file '/usr/local/lib/lua/5.1/blam.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/blam.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/sni/.local/share/nvim/lazy/blam.nvim/lua/blam.lua:76: in function 'setup'
        [string ":lua"]:1: in main chunk
```

The plugin has been compiled correctly:

```
$ ls /home/sni/.local/share/nvim/lazy/blam.nvim/target/release
build/  deps/  examples/  incremental/  libblam_core.d  libblam_core.so*
```

Where should I look at?

**Comment by willothy** [comment]
There should be a `lua` folder (/home/sni/.local/share/nvim/lazy/blam.nvim/lua/) that contains the compiled .so file, core.so, and the lua file. Mind checking if that exists? 

Did you use the build command `make`, or `cargo build`? The makefile is required to deploy the dylib to the correct location.

**Comment by pipoprods** [comment]
That was it!

The `lua/blam` folder was empty.
The `make` command was originally run by lazy.vim (tried multiple times). I launched it manually and now it's OK.

Strange thing: I installed moveline.vim the same way (through lazy.vim) and everything went OK the first time…

Thanks for your help (and plugins) :slightly_smiling_face:

**Comment by willothy** [comment]
Awesome, I'm glad it worked out, and I appreciate your interest in my work! Yeah, occasionally Lazy has some issues rebuilding Rust projects - I'm not sure why that's the case, but I am working on a better build solution for `nvim-utils` so that Makefiles won't be necessary anymore and the build process should be less prone to failure. 

Also, when building automatically doesn't work, I'm usually able to get the plugin built properly by selecting it in Lazy and using `gb` to rebuild, but doing it manually works too :)
